# Generated by Django 4.2.3 on 2023-08-31 17:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0004_remove_dateentry_date_dateentry_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateentry',
            name='question',
            field=models.CharField(default=django.utils.timezone.now, max_length=520),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 19, 47, 25, 864590), verbose_name='date published'),
        ),
    ]
