# Generated by Django 4.2.3 on 2023-09-08 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0006_alter_dateentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 19, 13, 32, 499405), verbose_name='date published'),
        ),
    ]
