# Generated by Django 4.2.5 on 2023-09-08 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0008_dateentry_resolutionvidlink_alter_dateentry_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isCorrect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 21, 14, 39, 911424), verbose_name='date published'),
        ),
    ]
