# Generated by Django 4.2.5 on 2023-09-08 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vidPlatform', '0009_choice_iscorrect_alter_dateentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='isCorrect',
            field=models.BooleanField(verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 21, 23, 51, 444135), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidPlatform.choice')),
            ],
        ),
    ]
