# Generated by Django 4.2.5 on 2023-10-26 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0011_alter_dateentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='isCorrect',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='end_date',
            field=models.DateField(help_text='From beginning of this day on no longer active', verbose_name='end quiz on'),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 18, 7, 5, 566718), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='resolutionVidLink',
            field=models.CharField(help_text='Youtube Video Code only', max_length=64),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='start_date',
            field=models.DateField(help_text='Is active from this day on', verbose_name='start quiz on'),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='videoLink',
            field=models.CharField(help_text='Youtube Video Code only', max_length=64),
        ),
    ]
