# Generated by Django 4.2.5 on 2023-10-26 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0012_alter_choice_iscorrect_alter_dateentry_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 18, 7, 13, 40706), verbose_name='date published'),
        ),
    ]
