# Generated by Django 4.2.5 on 2023-11-17 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0014_alter_dateentry_pub_date_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 18, 13, 1, 939981), verbose_name='date published'),
        ),
    ]
