# Generated by Django 4.2.5 on 2023-11-19 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0015_alter_dateentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 14, 1, 5, 436447), verbose_name='date published'),
        ),
    ]
