# Generated by Django 4.2.5 on 2023-12-04 10:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0017_alter_dateentry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 11, 16, 35, 350864), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentYear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(13), django.core.validators.MinValueValidator(5)]),
        ),
    ]
