# Generated by Django 4.2.5 on 2023-12-04 21:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0018_alter_dateentry_pub_date_alter_student_studentyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 22, 22, 34, 291032), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.CharField(max_length=1, verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentYear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(13), django.core.validators.MinValueValidator(5)], verbose_name='Jahrgang'),
        ),
    ]
