# Generated by Django 4.2.5 on 2023-12-04 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidPlatform', '0019_alter_dateentry_pub_date_alter_student_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 22, 38, 14, 88281), verbose_name='date published'),
        ),
    ]
